/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import EDA.Comentario;
import EDA.UsuDados;
import EDA.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author weiss
 */
public class TelaVisualizarComentariosUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaVisualizarComentariosUsuario
     */
    
    TelaInformacoesProprietario tela;
    TelaBuscarProprietario telaBusca;
    
    public TelaVisualizarComentariosUsuario() {
        initComponents();
    }
    
    public TelaVisualizarComentariosUsuario(TelaInformacoesProprietario tela, UsuDados proprietario){
        this();
        this.tela = tela;
        
        DefaultTableModel model = (DefaultTableModel)jtb_Comentarios.getModel();
        model.setRowCount(0);
        
        ArrayList<Usuario> aux = Negocio.NegocioFacade.listaUsuarios();
        
        for(Usuario a : aux){
            if(a.getCpf().equals(proprietario.getCpf())){
                for(Comentario c : a.getComentUsu()){
                    if(c.getComment() != ""){
                        String usuario = "";
                        int i = 0;
                        for(i = 0; i < c.getComment().length() && c.getComment().charAt(i) != '&'; i++){
                            usuario += c.getComment().charAt(i);
                        }
                        i++;
                        String comentario = "";
                        for(; i < c.getComment().length(); i++){
                            comentario += c.getComment().charAt(i);
                        }
                        model.addRow(new Object[]{ usuario, comentario });
                    }
                }
            }
        }
        
        jtb_Comentarios.setModel(model);
        
    }
    
    public TelaVisualizarComentariosUsuario(TelaBuscarProprietario tela, UsuDados proprietario){
        this();
        this.telaBusca = tela;
        
        DefaultTableModel model = (DefaultTableModel)jtb_Comentarios.getModel();
        model.setRowCount(0);
        
        ArrayList<Usuario> aux = Negocio.NegocioFacade.listaUsuarios();
        
        for(Usuario a : aux){
            if(a.getCpf().equals(proprietario.getCpf())){
                for(Comentario c : a.getComentUsu()){
                    if(c.getComment() != ""){
                        String usuario = "";
                        int i = 0;
                        for(i = 0; i < c.getComment().length() && c.getComment().charAt(i) != '&'; i++){
                            usuario += c.getComment().charAt(i);
                        }
                        i++;
                        String comentario = "";
                        for(; i < c.getComment().length(); i++){
                            comentario += c.getComment().charAt(i);
                        }
                        model.addRow(new Object[]{ usuario, comentario });
                    }
                }
            }
        }
        
        jtb_Comentarios.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Comentarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                Fechando(evt);
            }
        });

        jtb_Comentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuário", "Comentário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb_Comentarios);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Expandir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Fechando(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Fechando
        // TODO add your handling code here:
        if(tela != null){
            tela.setEnabled(true);
        } else {
            telaBusca.setEnabled(true);
        }
    }//GEN-LAST:event_Fechando

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int index = jtb_Comentarios.getSelectedRow();
        if(index > -1){
            JTextArea msg = new JTextArea(10, 20);
            msg.setText((String)jtb_Comentarios.getModel().getValueAt(index, 1));
            msg.setLineWrap(true);
            msg.setWrapStyleWord(true);
            JScrollPane scrollPane = new JScrollPane(msg);
            JOptionPane.showMessageDialog(this, scrollPane, (String)jtb_Comentarios.getModel().getValueAt(index, 0), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarComentariosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarComentariosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarComentariosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarComentariosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVisualizarComentariosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb_Comentarios;
    // End of variables declaration//GEN-END:variables
}
