/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;
import Negocio.NegocioFacade;
import javax.swing.JOptionPane;
/**
 *
 * @author Leona
 */
public class TelaCadastroVendedor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroVendedor
     */
    public TelaCadastroVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_Email13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtf_Email14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtf_Email15 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtf_telefone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_endereco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtf_nome = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtf_cpf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtf_carteira = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtf_comentarios = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        btn_cadastrar = new java.awt.Button();
        btn_cancelar = new java.awt.Button();

        jLabel19.setText("CPF");

        jLabel20.setText("CPF");

        jLabel21.setText("CPF");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtf_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 241, 370, -1));

        jLabel13.setText("Telefone");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, -1, -1));
        getContentPane().add(jtf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 189, 370, -1));

        jLabel14.setText("Email");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 192, -1, -1));
        getContentPane().add(jtf_endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 215, 370, -1));

        jLabel15.setText("Endereço");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, -1, -1));

        jtf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 370, -1));

        jLabel16.setText("Nome");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));
        getContentPane().add(jtf_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 137, 370, -1));

        jLabel17.setText("CPF");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        getContentPane().add(jtf_carteira, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 163, 370, -1));

        jLabel18.setText("Carteiro motorista");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, -1, -1));
        getContentPane().add(jtf_comentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 267, 370, -1));

        jLabel22.setText("Comentários");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        label1.setFont(new java.awt.Font("Ebrima", 0, 48)); // NOI18N
        label1.setText("Cadastro de vendedor");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 18, -1, -1));

        btn_cadastrar.setLabel("Cadastra");
        btn_cadastrar.setName(""); // NOI18N
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        btn_cancelar.setLabel("Cancelar");
        btn_cancelar.setName(""); // NOI18N
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        String nome = jtf_nome.getText();
        String cpf  = jtf_cpf.getText();
        String telefone = jtf_telefone.getText();
        String email = jtf_email.getText();
        String endereco = jtf_endereco.getText();
        EDA.Comentario c = new EDA.Comentario(jtf_comentarios.getText());
        int carteira = Integer.parseInt(jtf_carteira.getText());
        if(NegocioFacade.checaCadastro(nome, "0000000", cpf, telefone, email)){
            EDA.Vendedor v = new EDA.Vendedor(nome, cpf, carteira, email, endereco, c, telefone);
            NegocioFacade.registrarVendedor(v);
        } else {
            JOptionPane.showMessageDialog(this, NegocioFacade.getStatus().getErro(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void jtf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_cadastrar;
    private java.awt.Button btn_cancelar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JTextField jtf_Email13;
    private javax.swing.JTextField jtf_Email14;
    private javax.swing.JTextField jtf_Email15;
    private javax.swing.JTextField jtf_carteira;
    private javax.swing.JTextField jtf_comentarios;
    private javax.swing.JTextField jtf_cpf;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_endereco;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_telefone;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
