/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Apresentacao.Comparadores.AnoVeiculoComparator;
import Apresentacao.Comparadores.MaiorPrecoVeiculoComparator;
import Apresentacao.Comparadores.MarcaVeiculoComparator;
import Apresentacao.Comparadores.MenorPrecoVeiculoComparator;
import Apresentacao.Comparadores.ModeloVeiculoComparator;
import Negocio.NegocioFacade;
import EDA.VendaVeiculo;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author weiss
 */
public class TelaBuscarVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form TelaBuscarVeiculo
     */
    TelaNegocio tela;
    
    public TelaBuscarVeiculo() {
        initComponents();
        
        jtb_Veiculos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        ButtonGroup group = new ButtonGroup();
        group.add(jrb_Marca);
        group.add(jrb_Modelo);
        group.add(jrb_Ano);
        group.add(jrb_MenorPreco);
        group.add(jrb_MaiorPreco);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jtb_Veiculos.setDefaultRenderer(Object.class, centerRenderer);
        
    }
    
    public TelaBuscarVeiculo(TelaNegocio tela){
        this();
        this.tela = tela;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrb_Ano = new javax.swing.JRadioButton();
        jrb_Modelo = new javax.swing.JRadioButton();
        jrb_Marca = new javax.swing.JRadioButton();
        jrb_MenorPreco = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrb_MaiorPreco = new javax.swing.JRadioButton();
        btn_Confirmar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_Veiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                Fechando(evt);
            }
        });

        jrb_Ano.setText("Ano");
        jrb_Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_AnoActionPerformed(evt);
            }
        });

        jrb_Modelo.setText("Modelo");
        jrb_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ModeloActionPerformed(evt);
            }
        });

        jrb_Marca.setText("Marca");
        jrb_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_MarcaActionPerformed(evt);
            }
        });

        jrb_MenorPreco.setText("Menor preço");
        jrb_MenorPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_MenorPrecoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("Menu de busca de veiculos");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Ordenar por:");

        jrb_MaiorPreco.setText("Maior preço");
        jrb_MaiorPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_MaiorPrecoActionPerformed(evt);
            }
        });

        btn_Confirmar.setText("Confirmar");
        btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        jtb_Veiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Cor", "Ano", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtb_Veiculos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb_Modelo)
                                    .addComponent(jrb_Marca)
                                    .addComponent(jrb_MenorPreco)
                                    .addComponent(jrb_MaiorPreco)
                                    .addComponent(jrb_Ano))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrb_Marca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_Modelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_Ano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_MenorPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_MaiorPreco))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Confirmar)
                    .addComponent(btn_Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Fechando(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Fechando
        // TODO add your handling code here:
        tela.setEnabled(true);
    }//GEN-LAST:event_Fechando
        
    private void jrb_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ModeloActionPerformed
        // TODO add your handling code here:        
        ArrayList<VendaVeiculo> aux = NegocioFacade.listaVeiculos();        
        Collections.sort(aux, new ModeloVeiculoComparator());
        
        DefaultTableModel model = (DefaultTableModel)jtb_Veiculos.getModel();
        model.setRowCount(0);
        for(VendaVeiculo a : aux){
            model.addRow(new Object[]{ a.getVeiculo().getMarca(), a.getVeiculo().getModelo(),
                                   a.getVeiculo().getCor(), a.getVeiculo().getAno(), a.getPreco()});
        }
        
        jtb_Veiculos.setModel(model);
        
    }//GEN-LAST:event_jrb_ModeloActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void jrb_AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_AnoActionPerformed
        // TODO add your handling code here:        
        ArrayList<VendaVeiculo> aux = NegocioFacade.listaVeiculos();        
        Collections.sort(aux, new AnoVeiculoComparator());
        
        DefaultTableModel model = (DefaultTableModel)jtb_Veiculos.getModel();
        model.setRowCount(0);
        for(VendaVeiculo a : aux){
            model.addRow(new Object[]{ a.getVeiculo().getMarca(), a.getVeiculo().getModelo(),
                                   a.getVeiculo().getCor(), a.getVeiculo().getAno(), a.getPreco()});
        }
        
        jtb_Veiculos.setModel(model);
    }//GEN-LAST:event_jrb_AnoActionPerformed

    private void jrb_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_MarcaActionPerformed
        // TODO add your handling code here:
        ArrayList<VendaVeiculo> aux = NegocioFacade.listaVeiculos();        
        Collections.sort(aux, new MarcaVeiculoComparator());
        
        DefaultTableModel model = (DefaultTableModel)jtb_Veiculos.getModel();
        model.setRowCount(0);
        for(VendaVeiculo a : aux){
            model.addRow(new Object[]{ a.getVeiculo().getMarca(), a.getVeiculo().getModelo(),
                                   a.getVeiculo().getCor(), a.getVeiculo().getAno(), a.getPreco()});
        }
        
        jtb_Veiculos.setModel(model);
    }//GEN-LAST:event_jrb_MarcaActionPerformed

    private void jrb_MenorPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_MenorPrecoActionPerformed
        // TODO add your handling code here:
        ArrayList<VendaVeiculo> aux = NegocioFacade.listaVeiculos();        
        Collections.sort(aux, new MenorPrecoVeiculoComparator());
        
        DefaultTableModel model = (DefaultTableModel)jtb_Veiculos.getModel();
        model.setRowCount(0);
        for(VendaVeiculo a : aux){
            model.addRow(new Object[]{ a.getVeiculo().getMarca(), a.getVeiculo().getModelo(),
                                   a.getVeiculo().getCor(), a.getVeiculo().getAno(), a.getPreco()});
        }
        
        jtb_Veiculos.setModel(model);
    }//GEN-LAST:event_jrb_MenorPrecoActionPerformed

    private void jrb_MaiorPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_MaiorPrecoActionPerformed
        // TODO add your handling code here:
        ArrayList<VendaVeiculo> aux = NegocioFacade.listaVeiculos();        
        Collections.sort(aux, new MaiorPrecoVeiculoComparator());
        
       DefaultTableModel model = (DefaultTableModel)jtb_Veiculos.getModel();
       model.setRowCount(0);
        for(VendaVeiculo a : aux){
            model.addRow(new Object[]{ a.getVeiculo().getMarca(), a.getVeiculo().getModelo(),
                                   a.getVeiculo().getCor(), a.getVeiculo().getAno(), a.getPreco()});
        }
        
        jtb_Veiculos.setModel(model);
    }//GEN-LAST:event_jrb_MaiorPrecoActionPerformed

    private void btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarActionPerformed
        // TODO add your handling code here:
        
        int index = jtb_Veiculos.getSelectedRow();
        if(index != -1){
            new TelaEspecificacaoVeiculo(this, NegocioFacade.listaVeiculos().get(index)).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "É necessário selecionar um carro!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_ConfirmarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEspecificacaoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEspecificacaoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEspecificacaoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEspecificacaoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscarVeiculo().setVisible(true);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jrb_Ano;
    private javax.swing.JRadioButton jrb_MaiorPreco;
    private javax.swing.JRadioButton jrb_Marca;
    private javax.swing.JRadioButton jrb_MenorPreco;
    private javax.swing.JRadioButton jrb_Modelo;
    private javax.swing.JTable jtb_Veiculos;
    // End of variables declaration//GEN-END:variables
}
