/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import DAO.DAOFacade;
import javax.swing.ButtonGroup;

/**
 *
 * @author weiss
 */
public class TelaBuscarVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form TelaBuscarVeiculo
     */
    TelaNegocio tela;
    DAOFacade controlador;
    
    public TelaBuscarVeiculo() {
        initComponents();
        
        ButtonGroup group = new ButtonGroup();
        group.add(jrb_Ano);
        group.add(jrb_Marca);
        group.add(jrb_Modelo);
        group.add(jrb_MenorPreco);
        group.add(jrb_MaiorPreco);
        group.add(jrb_Nome);
        
        controlador = DAOFacade.getInstance();
        
    }
    
    public TelaBuscarVeiculo(TelaNegocio tela){
        this();
        this.tela = tela;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrb_Nome = new javax.swing.JRadioButton();
        jrb_Ano = new javax.swing.JRadioButton();
        jrb_Modelo = new javax.swing.JRadioButton();
        jrb_Marca = new javax.swing.JRadioButton();
        jrb_MenorPreco = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrb_MaiorPreco = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                Fechando(evt);
            }
        });

        jrb_Nome.setText("Nome");

        jrb_Ano.setText("Ano");

        jrb_Modelo.setText("Modelo");

        jrb_Marca.setText("Marca");

        jrb_MenorPreco.setText("Menor preço");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("Menu de busca de veiculos");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Ordenar por:");

        jrb_MaiorPreco.setText("Maior preço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_Ano)
                            .addComponent(jrb_Nome)
                            .addComponent(jrb_Modelo)
                            .addComponent(jrb_Marca)
                            .addComponent(jrb_MenorPreco)
                            .addComponent(jrb_MaiorPreco))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jrb_Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_Ano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_Modelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_Marca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_MenorPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_MaiorPreco)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Fechando(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Fechando
        // TODO add your handling code here:
        tela.setEnabled(true);
    }//GEN-LAST:event_Fechando

    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jrb_Ano;
    private javax.swing.JRadioButton jrb_MaiorPreco;
    private javax.swing.JRadioButton jrb_Marca;
    private javax.swing.JRadioButton jrb_MenorPreco;
    private javax.swing.JRadioButton jrb_Modelo;
    private javax.swing.JRadioButton jrb_Nome;
    // End of variables declaration//GEN-END:variables
}
